# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 19:54
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('answer', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.CharField(max_length=100)),
                ('time', models.DecimalField(decimal_places=3, default=0.0, max_digits=6)),
                ('result', models.BooleanField()),
                ('performance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectic.Question')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auto_id', models.IntegerField(default=3000000)),
                ('created_datetime', models.DateTimeField(default=datetime.datetime.now)),
                ('performance', models.DecimalField(decimal_places=3, default=0.0, max_digits=10)),
                ('accumulated_score', models.IntegerField(default=0)),
                ('qes_possible', models.IntegerField(default=0)),
                ('qes_complete', models.IntegerField(default=0)),
                ('finished', models.BooleanField(default=False)),
                ('all_correct', models.BooleanField(default=False)),
                ('merit', models.BooleanField(default=False)),
                ('distinction', models.BooleanField(default=False)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectic.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lecturer', models.BooleanField(default='False')),
                ('matric_number', models.CharField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='questionattempt',
            name='quiz_attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectic.QuizAttempt'),
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lectic.Quiz'),
        ),
    ]
