# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='performance',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=10),
        ),
    ]
