# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0002_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lectic.Module'),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
