# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0003_auto_20190819_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
