# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0003_quizattempt_performance'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='qes_possible',
            field=models.IntegerField(default=0),
        ),
    ]
