# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0004_userprofile_coins'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='coins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
