# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0006_quizattempt_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='accumulated_score',
            field=models.IntegerField(default=0),
        ),
    ]
