# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-06 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0008_quizattempt_all_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='distinction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='merit',
            field=models.BooleanField(default=False),
        ),
    ]
