# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-12 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lectic', '0010_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='matric_number',
            field=models.CharField(max_length=8),
        ),
    ]
